// verify-export.browser.js: checks a FeelingWise Receipts export against itself, in a browser.
//
// Copyright 2026 FeelingWise. Licensed under the Apache License, Version 2.0;
// see the LICENSE file beside this one.
//
// GENERATED by scripts/build-standalone-verifier.ts in the FeelingWise tree,
// from the same text as verify-export.mjs: the CORE every export embeds and
// the compiled RFC 3161 reader. Loaded by index.html beside it. Exposes one
// global, window.FWVerifier, with parseExport, verifyExportText and describe.
// Runs offline and contacts nothing.

(function () {
'use strict';

const PAYLOAD_OPEN = '<script type="application/json" id="fw-export-data">';

/** The rows a reader reads, as a browser's textContent would give them. Byte-synced with extractProvenanceRows in html-export.ts. */
function provenanceDocument(html) {
  const nodes = [];
  // dd AND p — the summary rows are <dd>, the disclosure block is a <p>. This
  // shim is the THIRD copy of that set (the builder's regex in html-export.ts
  // and readProvenanceRows in verifier-core-source.ts are the other two); all
  // three must name the same tags, or a file the browser reads as ok reads as
  // broken here. Matching <dd> alone did exactly that, found 2026-09-08.
  const re = /<(?:dd|p) data-fw-prov="([a-zA-Z]+)">([\s\S]*?)<\/(?:dd|p)>/g;
  let m;
  while ((m = re.exec(html)) !== null) {
    const name = m[1];
    const text = m[2]
      .replace(/<[^>]*>/g, '')
      .replace(/&#39;/g, "'").replace(/&quot;/g, '"').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
    nodes.push({ getAttribute() { return name; }, textContent: text });
  }
  // fwNoHtml says the difference between "the page has no provenance rows"
  // and "there is no page": a bare JSON envelope is the second, and the
  // manifest's row digest cannot be checked against it at all.
  return { querySelectorAll() { return nodes; }, fwNoHtml: html === '' };
}

/** An envelope is an object with a records array and a public key; anything else is not an export, whatever it parses as. */
function envelopeOf(json) {
  const data = JSON.parse(json);
  if (!data || typeof data !== 'object' || Array.isArray(data)) throw new Error('not a FeelingWise export: the payload is not an object');
  if (!Array.isArray(data.records)) throw new Error('not a FeelingWise export: no records array');
  if (!data.publicKeyJwk || typeof data.publicKeyJwk !== 'object') throw new Error('not a FeelingWise export: no public key');
  return data;
}

/** Reads the export payload out of an HTML export, or a bare JSON envelope. */
function parseExport(text) {
  const trimmed = text.trimStart();
  if (trimmed.startsWith('{')) return { data: envelopeOf(trimmed), html: '' };
  const start = text.indexOf(PAYLOAD_OPEN);
  if (start < 0) throw new Error('not a FeelingWise export: no fw-export-data payload');
  const from = start + PAYLOAD_OPEN.length;
  const end = text.indexOf('</script>', from);
  if (end < 0) throw new Error('not a FeelingWise export: payload never closes');
  return { data: envelopeOf(text.slice(from, end)), html: text };
}

function createVerifier(document) {
  // ---- CORE (verbatim from src/forensics/verifier-core-source.ts) ----

  function hex(buf){return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,'0')).join('');}
  async function sha256(s){return hex(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(s)));}
  function b64uToBytes(s){
    s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';
    var raw=atob(s),out=new Uint8Array(raw.length);
    for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);
    return out;
  }
  function canonicalPayload(r){
    return JSON.stringify({
      id:r.id,timestamp:r.timestamp,platform:r.platform,
      originalText:r.originalText,originalHash:r.originalHash,originalLength:r.originalLength,
      neutralizedText:r.neutralizedText,author:r.author,postUrl:r.postUrl,
      techniques:r.techniques,overallScore:r.overallScore,
      userAgeCategory:r.userAgeCategory,aiSource:r.aiSource,feedSource:r.feedSource,
      aiModel:r.aiModel||'',aiProvider:r.aiProvider||'',
      detectionMode:r.detectionMode||'',configSnapshot:r.configSnapshot||null,
      prevRecordHash:r.prevRecordHash||'',chainPosition:typeof r.chainPosition==='number'?r.chainPosition:-1,
      verdict:r.verdict,skipReason:r.skipReason,
      kind:r.kind,parentVideoId:r.parentVideoId,environment:r.environment,
      priorChainHash:r.priorChainHash,resetReason:r.resetReason,
      publicKeyFingerprint:r.publicKeyFingerprint,
      topic:r.topic,sourceCategory:r.sourceCategory,
      parentRecordId:r.parentRecordId,commentDepth:r.commentDepth,
      roomAuthor:r.roomAuthor,roomCaption:r.roomCaption,roomUrl:r.roomUrl,
      harmFloor:r.harmFloor,failureKind:r.failureKind,cap:r.cap,
      metrics:r.metrics,
      anchorUrl:r.anchorUrl,
      overrideOrigin:r.overrideOrigin,
      visualApplied:r.visualApplied,
      videoContext:r.videoContext,
      accountType:r.accountType,
      sourceContainer:r.sourceContainer,
      observedSequence:r.observedSequence,
      viewportSeenAt:r.viewportSeenAt,
      surfaceSessionId:r.surfaceSessionId,
      imageContext:r.imageContext,
      surfaceOrigin:r.surfaceOrigin,
      textCapture:r.textCapture,
      mediaUrls:r.mediaUrls,
      decision:r.decision,
      reader:r.reader,
      buildId:r.buildId
    });
  }
  async function importPubKey(jwk){
    return crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);
  }
  async function fingerprintJwk(jwk){
    if(!jwk||typeof jwk.x!=='string'||typeof jwk.y!=='string'){
      throw new Error('embedded public key has no P-256 coordinates');
    }
    return (await sha256(jwk.x+'|'+jwk.y)).slice(0,16);
  }
  async function importVerifiedPubKey(jwk,declaredFingerprint){
    var derived=await fingerprintJwk(jwk);
    if(typeof declaredFingerprint!=='string'||derived!==declaredFingerprint){
      throw new Error('embedded public-key fingerprint mismatch');
    }
    return {pubKey:await importPubKey(jwk),fingerprint:derived};
  }
  // keys: every key the file carries, by fingerprint ({fp: CryptoKey}); a
  // bare CryptoKey is the file's own key alone. A record is checked under
  // the key its fingerprint names (since 2026-09-03 a file carries the
  // keys of earlier generations recovered with their records); a record
  // whose key is not in the file verifies by hash only, never fails.
  // A withheld record (register item 20 part 1): its content left the file,
  // so its hash cannot be recomputed here. It is accepted only when a signed
  // redaction marker in the same file names its id and its integrityHash;
  // the marker's own signature is checked like any record's.
  function redactionOf(marker){
    if(!marker||marker.kind!=='redaction-marker') return null;
    var m=/\brecord=(\S+) recordHash=([0-9a-f]{64}) fields=(\S+)/.exec(marker.originalText||'');
    return m?{recordId:m[1],recordHash:m[2],fields:m[3].split(','),markerId:marker.id}:null;
  }
  function redactionIndex(records){
    var idx={};
    for(var i=0;i<(records||[]).length;i++){var r=redactionOf(records[i]);if(r)idx[r.recordId]=r;}
    return idx;
  }
  async function verifyOne(rec, keys, currentFingerprint, redactions){
    if(rec&&rec.redacted){
      var red=redactions&&redactions[rec.id];
      if(!red||red.recordHash!==rec.integrityHash||red.markerId!==rec.redacted.markerId) return {ok:false,reason:'redaction-unattested'};
      // The hash cannot be recomputed — the content it covers has left the
      // file — so the signature over it is the only thing here that says the
      // install made this record rather than someone else. It was not being
      // checked at all: a redacted record earned its tick from a marker naming
      // its id and a string comparison. Checking it costs one verify and turns
      // "a marker mentions this" into "the install signed this hash".
      if(rec.signature&&currentFingerprint){
        var rkeys=keys&&typeof keys.type==='string'?{}:(keys||{});
        var rkey=rkeys[rec.publicKeyFingerprint||currentFingerprint]||rkeys[currentFingerprint];
        if(rkey){
          var rok=false;
          try{ rok=await crypto.subtle.verify({name:'ECDSA',hash:{name:'SHA-256'}},rkey,b64uToBytes(rec.signature),new TextEncoder().encode(rec.integrityHash)); }catch(e){ rok=false; }
          if(!rok) return {ok:false,reason:'tampered'};
        }
      }
      return {ok:true,redacted:true,markerId:red.markerId};
    }
    var recomputed=await sha256(canonicalPayload(rec));
    if(recomputed!==rec.integrityHash) return {ok:false,reason:'tampered'};
    // A recomputed unkeyed hash is structural evidence, not authentication.
    // Keep unsigned/unknown-key records readable, but never let them make the
    // overall result green.
    if(!rec.signature) return {ok:true,unverified:true,unsigned:true,reason:'unsigned'};
    if(!currentFingerprint){
      return {ok:true,unverified:true,unverifiedSignature:true,reason:'signature-unverified'};
    }
    var byFp=keys&&typeof keys.type==='string'?{}:(keys||{});
    if(keys&&typeof keys.type==='string') byFp[currentFingerprint]=keys;
    var fp=rec.publicKeyFingerprint||currentFingerprint;
    var pubKey=byFp[fp];
    if(!pubKey){
      return {ok:true,unverified:true,priorKey:true,reason:'prior-key',fingerprint:fp};
    }
    var okSig=false;
    try{
      var sig=b64uToBytes(rec.signature);
      okSig=await crypto.subtle.verify({name:'ECDSA',hash:{name:'SHA-256'}},pubKey,sig,
        new TextEncoder().encode(rec.integrityHash));
    }catch(_err){
      okSig=false;
    }
    if(!okSig){
      if(!rec.publicKeyFingerprint){
        // The signature WAS checked and it did not verify. The record names no
        // key, so this cannot be called forgery — a record written before the
        // fingerprint field existed may have been signed under a key that has
        // since rotated, and the file carries a different one. But it is not
        // the same fact as "there was no key to check against", which is what
        // 'signature-unverified' means at the branch above, and both were
        // reported with that one word under a verdict line reading "no
        // signature failed". A signature was run and it failed.
        return {ok:true,unverified:true,unverifiedSignature:true,signatureRejected:true,reason:'signature-did-not-verify',fingerprint:fp};
      }
      return {ok:false,reason:'key-mismatch'};
    }
    // A key that travelled in this file beside the records is checked for
    // self-consistency only (its fingerprint matches its own bytes). The
    // signature verifies; the file cannot say whose key it is. The file's own
    // key is the one with a first-seen stamp from outside authorities, so the
    // two are told apart (evidence-gap register item 12, 2026-09-06).
    if(fp!==currentFingerprint) return {ok:true,carriedKey:true,fingerprint:fp};
    return {ok:true};
  }
  async function verifyChain(records,perRecord){
    // A link is a hash: record N names its predecessor by integrityHash. The
    // walk resolves each link against every record in the file, wherever it
    // sits, because a file can hold more than one run of the same chain:
    // after a record loss and recovery the install signs new records at
    // positions it had already used (2026-09-03, the owner's file: 1,062
    // positions held twice or three times, every link resolving to a record
    // in the file). Those are reported as branches, never as tampering.
    // A predecessor that is not in the file is expected for a filtered
    // export (applyExportGate drops pass/skipped records) and is counted,
    // not flagged. A seam (consecutive positions, broken link, predecessor
    // absent) is a restart: where both signatures verify the install signed
    // both records itself; where the file does not carry the key (the
    // owner's imported generations, 2026-09-03) the restart cannot be
    // confirmed by signature and is counted as unattributed. A seam is never
    // a failure on its own: a modified record fails its own hash, a forged
    // one fails its signature, and those are reported per record.
    var hashes={};
    for(var h=0;h<records.length;h++){
      if(typeof records[h].integrityHash==='string') hashes[records[h].integrityHash]=true;
    }
    var seenPos={},branches=0,restarts=0,unattributed=0,outside=0;
    for(var i=0;i<records.length;i++){
      var cur=records[i];
      if(typeof cur.chainPosition==='number'){
        var posKey=(cur.publicKeyFingerprint||'')+':'+cur.chainPosition;
        if(seenPos[posKey]) branches++; else seenPos[posKey]=true;
      }
      if(i===0||typeof cur.prevRecordHash!=='string') continue;
      if(hashes[cur.prevRecordHash]) continue;
      var prev=records[i-1];
      var contiguous=typeof prev.chainPosition==='number'
        && typeof cur.chainPosition==='number'
        && cur.chainPosition === prev.chainPosition + 1;
      if(!contiguous){ outside++; continue; }
      var a=perRecord&&perRecord[i-1],b=perRecord&&perRecord[i];
      var signedBoth=!!(a&&b&&a.ok&&!a.unverified&&b.ok&&!b.unverified);
      if(!signedBoth) unattributed++;
      restarts++;
    }
    return {ok:true,branches:branches,restarts:restarts,unattributed:unattributed,outside:outside};
  }
  // Completeness, recomputed by the recipient rather than read off the
  // page-one summary. The summary is static HTML written at export time; if
  // the payload is edited afterwards the two disagree, and only this one is
  // computed from the records the reader is actually looking at.
  //
  // Mirrors computeChainCoverage in html-export.ts: runs are split at every
  // position reset, because a month rotation legitimately restarts at 0.
  // A record the person typed in, not one the software observed. flagPostManually
  // (src/forensics/manual-flag.ts) builds it from a web address and the user's
  // own words and appends it to the same signed chain, so nothing in the
  // cryptography separates it from a capture. Only the label does.
  function isManualRecord(r){
    return !!r&&(r.feedSource==='manual'
      ||(typeof r.detectionMode==='string'&&r.detectionMode.indexOf('manual')===0)
      ||(typeof r.id==='string'&&r.id.indexOf('fr-manual-')===0));
  }
  function coverageFromRecords(records){
    var chained=[];
    for(var i=0;i<records.length;i++){
      var r=records[i];
      if(typeof r.chainPosition!=='number'||r.chainPosition<0) continue;
      if(r.chainAnchor==='pre-rekey') continue;
      chained.push(r.chainPosition);
    }
    if(!chained.length) return {present:0,missingBefore:0,gapsInside:0};
    var runs=[],cur=[],prev=-Infinity;
    for(var j=0;j<chained.length;j++){
      if(chained[j]<=prev){ if(cur.length)runs.push(cur); cur=[]; }
      cur.push(chained[j]); prev=chained[j];
    }
    if(cur.length)runs.push(cur);
    var missingBefore=0,gapsInside=0;
    for(var k=0;k<runs.length;k++){
      var run=runs[k],first=run[0],last=run[run.length-1];
      if(first>0) missingBefore+=first;
      var seen={},n=0;
      for(var m=0;m<run.length;m++){ if(!seen[run[m]]){seen[run[m]]=true;n++;} }
      var span=last-first+1;
      if(span>n) gapsInside+=span-n;
    }
    return {
      present:chained.length,
      firstPosition:runs[0][0],
      lastPosition:runs[runs.length-1][runs[runs.length-1].length-1],
      missingBefore:missingBefore,
      gapsInside:gapsInside
    };
  }
  // What the independent timestamps say about what is missing.
  //
  // This is the only completeness evidence in the file that the person holding
  // it could not have produced. An anchor names a chain position and the exact
  // record hash at that position; both were signed by an authority with no
  // stake here. So an anchor whose record is absent, or whose position sits
  // past the last record present, is third-party evidence that this file does
  // not carry everything the chain held. Removing the tail of a chain used to
  // leave no trace at all; against an anchor it does.
  function anchorFindings(records,anchors){
    var out={checked:0,notInFile:0,beyondTail:0,beyondPosition:-1,lastPosition:-1};
    if(!anchors||!anchors.length) return out;
    var hashes={},maxPos=-1;
    for(var i=0;i<records.length;i++){
      var r=records[i];
      if(typeof r.integrityHash==='string') hashes[r.integrityHash]=true;
      if(typeof r.chainPosition==='number'&&r.chainPosition>maxPos&&r.chainAnchor!=='pre-rekey'){
        maxPos=r.chainPosition;
      }
    }
    out.lastPosition=maxPos;
    // Counted by the RECORD each anchor points at, not by the anchor. A round
    // asks two authorities about one chain head, so counting anchors would
    // report one missing record as two.
    var missing={};
    for(var a=0;a<anchors.length;a++){
      var an=anchors[a];
      out.checked++;
      if(!hashes[an.anchoredIntegrityHash]) missing[an.anchoredIntegrityHash]=true;
      if(typeof an.anchoredChainPosition==='number'&&maxPos>=0&&an.anchoredChainPosition>maxPos){
        var gap=an.anchoredChainPosition-maxPos;
        if(gap>out.beyondTail){ out.beyondTail=gap; out.beyondPosition=an.anchoredChainPosition; }
      }
    }
    out.notInFile=Object.keys(missing).length;
    return out;
  }
  // What the file says it is. A report made through the export gate states
  // its own selection: how many records it holds of how many the install
  // had, and how many the gate left out. When that statement is present,
  // covers every record in the file, and the predecessors missing from the
  // chain are no more than the records it says it left out, those missing
  // links are the report's own doing and not a loss: the file reads as a
  // report, verified, not as partial. The statement sits inside the signed
  // manifest, so it is the signer's claim, not an editor's (2026-09-06, the
  // owner's first look at his own report on the check page: 95 of 943
  // records, 89 links outside, and a PARTIAL he could not explain).
  // The record kinds a file may hold BEYOND the content its selection counts.
  // A marker is written by the install to explain something about the chain —
  // a redaction, a prune, a rotation, a gap — and it is not one of the
  // observations a report says it included.
  var SELECTION_EXTRA_KINDS={
    'reset-marker':1,'month-rotation-marker':1,'prune-marker':1,'gap-marker':1,
    'heartbeat-marker':1,'import-marker':1,'repair-marker':1,'redaction-marker':1,
    'reconcile-marker':1
  };
  /**
   * The file's own statement of what it left out, accepted only when the file
   * really holds what it says.
   *
   * The count compares against CONTENT records. It compared against every
   * record in the file, so redacting one record inside a filtered report broke
   * it: the redaction marker is an extra record, included no longer equalled
   * the file's length, and this returned null. The report then lost the signed
   * selection that explains its own gaps, its unresolved links read as
   * unexplained, and a sound file fell from VERIFIED to partially verified for
   * doing the thing the product tells people to do with a name they want out.
   * Measured on a four-record report: with the marker, selectionOf null and
   * state partial; without it, a selection of 2 of 4 and state verified.
   */
  function selectionOf(data,recordCount){
    var s=data&&data.selection;
    if(!s||typeof s!=='object') return null;
    if(typeof s.included!=='number'||typeof s.totalSource!=='number') return null;
    var content=recordCount;
    if(typeof recordCount!=='number'&&recordCount&&typeof recordCount.length==='number'){
      content=0;
      for(var i=0;i<recordCount.length;i++){
        var k=recordCount[i]&&recordCount[i].kind;
        if(!k||!SELECTION_EXTRA_KINDS[k]) content++;
      }
    }
    if(s.included!==content||s.totalSource<s.included) return null;
    return {included:s.included,totalSource:s.totalSource,leftOut:s.totalSource-s.included};
  }
  // The third argument is optional so the two-argument callers in the test
  // suite keep working. chain.outside was computed and never consulted, which
  // is how a file with records removed from it printed VERIFIED.
  function verificationState(perRecord,chain,extra){
    if(!chain.ok||perRecord.some(function(r){return !r.ok;})) return 'failed';
    if(perRecord.some(function(r){return r.unverified;})) return 'partial';
    if(perRecord.some(function(r){return r.carriedKey;})) return 'partial';
    if(chain.branches>0||chain.restarts>0) return 'partial';
    if(chain.outside>0){
      var sel=extra&&extra.selection;
      if(!sel||chain.outside>sel.leftOut) return 'partial';
    }
    if(extra&&extra.anchors&&(extra.anchors.notInFile>0||extra.anchors.beyondTail>0)) return 'partial';
    // The arithmetic that proves records are missing was computed and never
    // consulted. coverageFromRecords counts the positions absent before the
    // first record it holds and the holes inside, and a file starting at
    // position 500 could still read VERIFIED — the chain walk cannot see it,
    // because a missing head leaves nothing pointing at it and a missing run
    // leaves each surviving link still resolving.
    //
    // A filtered report is allowed to have holes: applyExportGate drops passed
    // records on purpose and the selection says so under signature. So this
    // reads exactly as chain.outside does — a gap a stated selection accounts
    // for is not a gap in what the file claims to be.
    if(extra&&extra.coverage&&(extra.coverage.missingBefore>0||extra.coverage.gapsInside>0)){
      var csel=extra&&extra.selection;
      var absent=extra.coverage.missingBefore+extra.coverage.gapsInside;
      if(!csel||absent>csel.leftOut) return 'partial';
    }
    return 'verified';
  }
  function chainNotes(chain,i18n,sel){
    var notes=[];
    var seams=(chain.branches||0)+(chain.restarts||0);
    if(seams>0) notes.push(i18n.chainNoteBranches.replace('{n}',String(seams)));
    if(chain.unattributed>0) notes.push(i18n.chainNoteUnattributed.replace('{n}',String(chain.unattributed)));
    if(chain.outside>0){
      if(sel&&chain.outside<=sel.leftOut&&i18n.chainNoteOutsideStated){
        notes.push(i18n.chainNoteOutsideStated.replace('{n}',String(chain.outside)).replace('{x}',String(sel.included)).replace('{y}',String(sel.totalSource)));
      }else{
        notes.push(i18n.chainNoteOutside.replace('{n}',String(chain.outside)));
      }
    }
    return notes;
  }
  // The signed manifest (evidence-gap register item 6). At export time the
  // install signs a digest over the envelope's records, anchors, keys, labels
  // and wording; here the same digests are recomputed from what the file
  // actually carries and the signature is checked under the file's own key.
  // The canonical form is a fixed-order array; attachSignedManifest in
  // html-export.ts builds the identical string.
  function manifestCanonical(m){return JSON.stringify([m.version,m.recordCount,m.recordsDigest,m.anchorsDigest,m.publicKeysDigest,m.techLabelsDigest,m.i18nDigest,m.publicKeyFingerprint,m.generatedAt,m.envelopeDigest,m.provenanceDigest]);}
  function nz(v){return v===undefined||v===null?null:v;}
  function readProvenanceRows(){
    var nodes=document.querySelectorAll('dd[data-fw-prov],p[data-fw-prov]');
    var out=[];
    for(var i=0;i<nodes.length;i++){
      out.push([nodes[i].getAttribute('data-fw-prov'),(nodes[i].textContent||'').replace(/\s+/g,' ').trim()]);
    }
    out.sort(function(a,b){return a[0]<b[0]?-1:a[0]>b[0]?1:0;});
    return out;
  }
  function envelopeCanonical(d){return JSON.stringify([nz(d.selection),nz(d.keyGenesis),nz(d.keyOrigins),nz(d.signingKeyCreatedAt),nz(d.precisionDisclosure),nz(d.fwVersion),nz(d.locale),nz(d.publicKeyJwk)]);}
  async function checkManifest(data,pubKey,fingerprint){
    var m=data.manifest;
    if(!m||typeof m!=='object') return 'missing';
    if(m.version===1) return 'legacy';
    if(m.version!==2) return 'version';
    if(m.publicKeyFingerprint!==fingerprint) return 'key';
    if(m.recordCount!==(data.records||[]).length) return 'records';
    if(m.recordsDigest!==await sha256(JSON.stringify(data.records||[]))) return 'records';
    if(m.anchorsDigest!==await sha256(JSON.stringify(data.anchors||[]))) return 'anchors';
    if(m.publicKeysDigest!==await sha256(JSON.stringify(data.publicKeys||[]))) return 'keys';
    if(m.techLabelsDigest!==await sha256(JSON.stringify(data.techLabels||{}))) return 'labels';
    if(m.i18nDigest!==await sha256(JSON.stringify(data.i18n||{}))) return 'wording';
    if(m.envelopeDigest!==await sha256(envelopeCanonical(data))) return 'provenance';
    // The rows a reader reads live in the HTML. A bare JSON envelope has none —
    // and that input form is advertised by this checker's own usage line, by
    // index.html and by FORMAT.md, which says outright that a bare envelope
    // "cannot fully verify". It was reading BROKEN (manifest: summary-rows),
    // because a digest over zero rows can never equal a digest over the page's
    // rows. Telling a recipient a good file is broken is the worst false alarm
    // this checker can raise, so the comparison is reported as not made rather
    // than failed. The real browser document never carries this flag, so the
    // in-page verifier is unaffected.
    if(document&&document.fwNoHtml===true) return 'no-rows';
    if(m.provenanceDigest!==await sha256(JSON.stringify(readProvenanceRows()))) return 'summary-rows';
    if(m.digest!==await sha256(manifestCanonical(m))) return 'digest';
    var okSig=false;
    try{
      okSig=await crypto.subtle.verify({name:'ECDSA',hash:{name:'SHA-256'}},pubKey,b64uToBytes(m.signature),new TextEncoder().encode(m.digest));
    }catch(_e){okSig=false;}
    return okSig?'ok':'signature';
  }
  // ---- END CORE ----
  return { importVerifiedPubKey, redactionIndex, verifyOne, verifyChain, anchorFindings, coverageFromRecords, verificationState, checkManifest, sha256, selectionOf };
}

// ---- RFC 3161 (compiled from src/forensics/rfc3161.ts by scripts/gen-rfc3161-inline.mjs; defines __FW_RFC3161__) ----
"use strict";
var __FW_RFC3161__ = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/forensics/rfc3161.ts
  var rfc3161_exports = {};
  __export(rfc3161_exports, {
    KNOWN_TSA_ROOTS: () => KNOWN_TSA_ROOTS,
    buildTimeStampReq: () => buildTimeStampReq,
    hexToBytes: () => hexToBytes,
    parseCertificate: () => parseCertificate,
    parseTimeStampResp: () => parseTimeStampResp,
    shortSubject: () => shortSubject,
    toHex: () => toHex,
    verifyAnchorBase64: () => verifyAnchorBase64,
    verifyTimeStampToken: () => verifyTimeStampToken
  });
  function derLength(n) {
    if (n < 128) return new Uint8Array([n]);
    if (n < 256) return new Uint8Array([129, n]);
    if (n < 65536) return new Uint8Array([130, n >> 8 & 255, n & 255]);
    throw new Error("der: length too large");
  }
  function derPrimitive(tag, body) {
    const lb = derLength(body.length);
    const out = new Uint8Array(1 + lb.length + body.length);
    out[0] = tag;
    out.set(lb, 1);
    out.set(body, 1 + lb.length);
    return out;
  }
  function derSequence(parts) {
    let total = 0;
    for (const p of parts) total += p.length;
    const body = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
      body.set(p, o);
      o += p.length;
    }
    return derPrimitive(48, body);
  }
  function derInteger(bytes) {
    let i = 0;
    while (i < bytes.length - 1 && bytes[i] === 0) i++;
    const v = bytes.subarray(i);
    const needsPad = v.length > 0 && (v[0] & 128) !== 0;
    const body = new Uint8Array(v.length + (needsPad ? 1 : 0));
    body.set(v, needsPad ? 1 : 0);
    return derPrimitive(2, body);
  }
  function hexToBytes(hex) {
    const s = hex.trim().toLowerCase();
    if (!/^[0-9a-f]+$/.test(s) || s.length % 2 !== 0) throw new Error("not hex");
    const out = new Uint8Array(s.length / 2);
    for (let i = 0; i < s.length; i += 2) out[i / 2] = parseInt(s.slice(i, i + 2), 16);
    return out;
  }
  function buildTimeStampReq(hashHex) {
    const hash = hexToBytes(hashHex);
    if (hash.length !== 32) throw new Error("expected a SHA-256 hash");
    const nonce = crypto.getRandomValues(new Uint8Array(8));
    nonce[0] &= 127;
    const sha256Oid = new Uint8Array([6, 9, 96, 134, 72, 1, 101, 3, 4, 2, 1]);
    const asn1Null = new Uint8Array([5, 0]);
    const der = derSequence([
      new Uint8Array([2, 1, 1]),
      derSequence([derSequence([sha256Oid, asn1Null]), derPrimitive(4, hash)]),
      derInteger(nonce),
      new Uint8Array([1, 1, 255])
    ]);
    return { der, nonceHex: toHex(nonce) };
  }
  var KNOWN_TSA_ROOTS = Object.freeze({
    // O=Free TSA, OU=Root CA, CN=www.freetsa.org. Self-signed, 2016-03-13 to 2041-03-07.
    a6379e7cecc05faa3cbf076013d745e327bbbaa38c0b9af22469d4701d18aabc: "FreeTSA (freetsa.org) Root CA",
    // DC=cz, O=CESNET CA, CN=CESNET CA Root. Self-signed.
    c0712e7f295d643e9aa6b72686dde19ab68169c22b63a13bf91580d9055262ab: "CESNET CA Root",
    // C=US, O=DigiCert Inc, CN=DigiCert Trusted Root G4.
    "33846b545a49c9be4903c60e01713c1bd4e4ef31ea65cd95d69e62794f30b941": "DigiCert Trusted Root G4",
    // C=GB, O=Sectigo Limited, CN=Sectigo Public Time Stamping Root R46.
    b53ac15cc1afb6e2ac06828f555bb3bf5bad8b2bac1733ce4cb7aafe729356de: "Sectigo Public Time Stamping Root R46"
  });
  function readTlv(b, off) {
    if (off + 1 > b.length) throw new Error("der: truncated at tag");
    const tag = b[off];
    let i = off + 1;
    if (i >= b.length) throw new Error("der: truncated at length");
    let len = b[i++];
    if (len & 128) {
      const n = len & 127;
      if (n === 0 || n > 4) throw new Error("der: unsupported length form");
      if (i + n > b.length) throw new Error("der: truncated length octets");
      len = 0;
      for (let k = 0; k < n; k++) len = len * 256 + b[i++];
    }
    const end = i + len;
    if (end > b.length) throw new Error("der: length exceeds buffer");
    return { tag, start: off, contentStart: i, length: len, end };
  }
  function children(b, t) {
    const out = [];
    let o = t.contentStart;
    while (o < t.end) {
      const c = readTlv(b, o);
      out.push(c);
      o = c.end;
    }
    return out;
  }
  function content(b, t) {
    return b.subarray(t.contentStart, t.end);
  }
  function bytesOf(b, t) {
    return b.subarray(t.start, t.end);
  }
  function toHex(b) {
    let s = "";
    for (let i = 0; i < b.length; i++) s += b[i].toString(16).padStart(2, "0");
    return s;
  }
  function readOid(b, t) {
    const v = content(b, t);
    if (v.length === 0) return "";
    const parts = [Math.floor(v[0] / 40), v[0] % 40];
    let acc = 0;
    for (let i = 1; i < v.length; i++) {
      acc = acc * 128 + (v[i] & 127);
      if ((v[i] & 128) === 0) {
        parts.push(acc);
        acc = 0;
      }
    }
    return parts.join(".");
  }
  function readIntegerHex(b, t) {
    let v = content(b, t);
    let i = 0;
    while (i < v.length - 1 && v[i] === 0) i++;
    v = v.subarray(i);
    return toHex(v);
  }
  function readGeneralizedTime(b, t) {
    var _a;
    const s = new TextDecoder().decode(content(b, t));
    const m = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\.\d{1,6})?Z$/.exec(s);
    if (!m) return null;
    return `${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}${(_a = m[7]) != null ? _a : ""}Z`;
  }
  function readUtcTime(b, t) {
    var _a;
    const s = new TextDecoder().decode(content(b, t));
    const m = /^(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})?Z$/.exec(s);
    if (!m) return null;
    const yy = Number(m[1]);
    const year = yy >= 50 ? 1900 + yy : 2e3 + yy;
    return `${year}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${(_a = m[6]) != null ? _a : "00"}Z`;
  }
  function readTime(b, t) {
    if (t.tag === 23) return readUtcTime(b, t);
    if (t.tag === 24) return readGeneralizedTime(b, t);
    return null;
  }
  var OID_SIGNED_DATA = "1.2.840.113549.1.7.2";
  var OID_CT_TST_INFO = "1.2.840.113549.1.9.16.1.4";
  var OID_ATTR_MESSAGE_DIGEST = "1.2.840.113549.1.9.4";
  var OID_ATTR_CONTENT_TYPE = "1.2.840.113549.1.9.3";
  var OID_EKU = "2.5.29.37";
  var OID_SUBJECT_KEY_ID = "2.5.29.14";
  var OID_KP_TIMESTAMPING = "1.3.6.1.5.5.7.3.8";
  var OID_RSA_ENCRYPTION = "1.2.840.113549.1.1.1";
  var OID_EC_PUBLIC_KEY = "1.2.840.10045.2.1";
  var DIGEST_BY_OID = Object.freeze({
    "1.3.14.3.2.26": "SHA-1",
    "2.16.840.1.101.3.4.2.1": "SHA-256",
    "2.16.840.1.101.3.4.2.2": "SHA-384",
    "2.16.840.1.101.3.4.2.3": "SHA-512"
  });
  var SIG_ALG_BY_OID = Object.freeze({
    "1.2.840.113549.1.1.5": { kind: "rsa", hash: "SHA-1" },
    "1.2.840.113549.1.1.11": { kind: "rsa", hash: "SHA-256" },
    "1.2.840.113549.1.1.12": { kind: "rsa", hash: "SHA-384" },
    "1.2.840.113549.1.1.13": { kind: "rsa", hash: "SHA-512" },
    "1.2.840.10045.4.3.2": { kind: "ecdsa", hash: "SHA-256" },
    "1.2.840.10045.4.3.3": { kind: "ecdsa", hash: "SHA-384" },
    "1.2.840.10045.4.3.4": { kind: "ecdsa", hash: "SHA-512" }
  });
  var CURVE_BY_OID = Object.freeze({
    "1.2.840.10045.3.1.7": { name: "P-256", size: 32 },
    "1.3.132.0.34": { name: "P-384", size: 48 },
    "1.3.132.0.35": { name: "P-521", size: 66 }
  });
  var RDN_LABELS = Object.freeze({
    "2.5.4.3": "CN",
    "2.5.4.6": "C",
    "2.5.4.7": "L",
    "2.5.4.8": "ST",
    "2.5.4.10": "O",
    "2.5.4.11": "OU",
    "1.2.840.113549.1.9.1": "emailAddress"
  });
  function rdnToString(b, nameTlv) {
    var _a;
    const parts = [];
    for (const rdn of children(b, nameTlv)) {
      for (const atv of children(b, rdn)) {
        const kids = children(b, atv);
        if (kids.length < 2) continue;
        const oid = readOid(b, kids[0]);
        const label = (_a = RDN_LABELS[oid]) != null ? _a : oid;
        const value = new TextDecoder().decode(content(b, kids[1]));
        parts.push(`${label}=${value}`);
      }
    }
    return parts.join(", ");
  }
  function parseCertificate(b, certTlv) {
    var _a;
    const cert = children(b, certTlv);
    const tbs = cert[0];
    const sigAlg = cert[1];
    const sigValue = cert[2];
    const tbsKids = children(b, tbs);
    let i = 0;
    if (((_a = tbsKids[0]) == null ? void 0 : _a.tag) === 160) i = 1;
    const serial = tbsKids[i++];
    i++;
    const issuer = tbsKids[i++];
    const validity = tbsKids[i++];
    const subject = tbsKids[i++];
    const spki = tbsKids[i++];
    const validityKids = children(b, validity);
    const notBefore = validityKids[0] ? readTime(b, validityKids[0]) : null;
    const notAfter = validityKids[1] ? readTime(b, validityKids[1]) : null;
    const spkiKids = children(b, spki);
    const algKids = children(b, spkiKids[0]);
    const publicKeyAlgOid = readOid(b, algKids[0]);
    const curveOid = publicKeyAlgOid === OID_EC_PUBLIC_KEY && algKids[1] ? readOid(b, algKids[1]) : null;
    const extendedKeyUsage = [];
    let ekuCritical = false;
    let subjectKeyIdentifierHex = null;
    for (let k = i; k < tbsKids.length; k++) {
      if (tbsKids[k].tag !== 163) continue;
      const extSeq = children(b, tbsKids[k])[0];
      if (!extSeq) continue;
      for (const ext of children(b, extSeq)) {
        const kids = children(b, ext);
        if (kids.length < 2) continue;
        const oid = readOid(b, kids[0]);
        if (oid === OID_SUBJECT_KEY_ID) {
          const octetSki = kids[kids.length - 1];
          try {
            const innerSki = readTlv(b, octetSki.contentStart);
            subjectKeyIdentifierHex = toHex(content(b, innerSki));
          } catch {
          }
          continue;
        }
        if (oid !== OID_EKU) continue;
        const critical = kids[1].tag === 1 && content(b, kids[1])[0] !== 0;
        const octet = kids[kids.length - 1];
        const inner = readTlv(b, octet.contentStart);
        for (const purpose of children(b, inner)) extendedKeyUsage.push(readOid(b, purpose));
        ekuCritical = critical;
      }
    }
    return {
      der: bytesOf(b, certTlv),
      tbsDer: bytesOf(b, tbs),
      serialHex: readIntegerHex(b, serial),
      issuerDer: bytesOf(b, issuer),
      subjectDer: bytesOf(b, subject),
      issuerString: rdnToString(b, issuer),
      subjectString: rdnToString(b, subject),
      notBefore,
      notAfter,
      spkiDer: bytesOf(b, spki),
      publicKeyAlgOid,
      curveOid,
      signatureAlgOid: readOid(b, children(b, sigAlg)[0]),
      // BIT STRING content begins with the count of unused bits, which is 0 here.
      signatureValue: content(b, sigValue).subarray(1),
      extendedKeyUsage,
      ekuCritical,
      subjectKeyIdentifierHex
    };
  }
  function sameBytes(a, c) {
    if (a.length !== c.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== c[i]) return false;
    return true;
  }
  function ecdsaDerToRaw(der, size) {
    let seq;
    try {
      seq = readTlv(der, 0);
    } catch {
      return null;
    }
    if (seq.tag !== 48) return null;
    const kids = children(der, seq);
    if (kids.length !== 2 || kids[0].tag !== 2 || kids[1].tag !== 2) return null;
    const out = new Uint8Array(size * 2);
    for (let n = 0; n < 2; n++) {
      let v = content(der, kids[n]);
      let i = 0;
      while (i < v.length - 1 && v[i] === 0) i++;
      v = v.subarray(i);
      if (v.length > size) return null;
      out.set(v, size * (n + 1) - v.length);
    }
    return out;
  }
  async function verifyWithCert(cert, signatureAlgOid, signature, signedBytes, fallbackHash) {
    var _a, _b;
    const alg = (_a = SIG_ALG_BY_OID[signatureAlgOid]) != null ? _a : signatureAlgOid === OID_RSA_ENCRYPTION && fallbackHash ? { kind: "rsa", hash: fallbackHash } : signatureAlgOid === OID_EC_PUBLIC_KEY && fallbackHash ? { kind: "ecdsa", hash: fallbackHash } : null;
    if (!alg) return { ok: false, detail: `unsupported signature algorithm ${signatureAlgOid}` };
    const spki = Uint8Array.from(cert.spkiDer);
    try {
      if (alg.kind === "rsa") {
        const key2 = await crypto.subtle.importKey(
          "spki",
          spki,
          { name: "RSASSA-PKCS1-v1_5", hash: { name: alg.hash } },
          false,
          ["verify"]
        );
        const ok2 = await crypto.subtle.verify(
          "RSASSA-PKCS1-v1_5",
          key2,
          Uint8Array.from(signature),
          Uint8Array.from(signedBytes)
        );
        return { ok: ok2, detail: ok2 ? `RSA ${alg.hash}` : `RSA ${alg.hash} did not verify` };
      }
      const curve = cert.curveOid ? CURVE_BY_OID[cert.curveOid] : null;
      if (!curve) return { ok: false, detail: `unsupported EC curve ${(_b = cert.curveOid) != null ? _b : "none"}` };
      const raw = ecdsaDerToRaw(signature, curve.size);
      if (!raw) return { ok: false, detail: "malformed ECDSA signature encoding" };
      const key = await crypto.subtle.importKey(
        "spki",
        spki,
        { name: "ECDSA", namedCurve: curve.name },
        false,
        ["verify"]
      );
      const ok = await crypto.subtle.verify(
        { name: "ECDSA", hash: { name: alg.hash } },
        key,
        Uint8Array.from(raw),
        Uint8Array.from(signedBytes)
      );
      return {
        ok,
        detail: ok ? `ECDSA ${curve.name} ${alg.hash}` : `ECDSA ${curve.name} ${alg.hash} did not verify`
      };
    } catch (err) {
      return { ok: false, detail: `verify failed: ${err.message}` };
    }
  }
  async function digest(hashName, data) {
    return new Uint8Array(await crypto.subtle.digest(hashName, Uint8Array.from(data)));
  }
  function parseTimeStampResp(der) {
    const top = readTlv(der, 0);
    const kids = children(der, top);
    const statusInfo = children(der, kids[0]);
    const statusBytes = content(der, statusInfo[0]);
    let status = 2;
    if (statusInfo[0].tag === 2) {
      let i = 0;
      while (i < statusBytes.length - 1 && statusBytes[i] === 0) i++;
      const trimmed = statusBytes.subarray(i);
      status = trimmed.length === 1 ? trimmed[0] : 2;
    }
    const token = kids.length > 1 ? bytesOf(der, kids[1]) : null;
    return { status, token };
  }
  async function verifyTimeStampToken(tokenDer, expectedHashHex, expectedNonceHex = null) {
    var _a, _b, _c, _d;
    const result = {
      ok: false,
      genTime: null,
      messageImprintHex: null,
      messageImprintAlgorithm: null,
      serialNumber: null,
      policyOid: null,
      nonceHex: null,
      signerSubject: null,
      signerCertSha256: null,
      rootCertSha256: null,
      knownRootName: null,
      checks: [],
      error: null
    };
    const add = (name, ok, detail) => {
      result.checks.push({ name, ok, detail });
    };
    if (typeof crypto === "undefined" || !crypto.subtle) {
      result.couldNotCheck = true;
      result.error = "this browser cannot run cryptographic checks here (Web Crypto is only available in a secure context)";
      return result;
    }
    let signedData;
    let b;
    try {
      b = tokenDer;
      const contentInfo = readTlv(b, 0);
      const ciKids = children(b, contentInfo);
      if (readOid(b, ciKids[0]) !== OID_SIGNED_DATA) {
        result.error = "token is not a CMS SignedData";
        return result;
      }
      signedData = children(b, ciKids[1])[0];
    } catch (err) {
      result.error = `token parse failed: ${err.message}`;
      return result;
    }
    try {
      const sdKids = children(b, signedData);
      const encap = sdKids[2];
      const encapKids = children(b, encap);
      if (readOid(b, encapKids[0]) !== OID_CT_TST_INFO) {
        result.error = "encapsulated content is not id-ct-TSTInfo";
        return result;
      }
      const eContentOctet = readTlv(b, encapKids[1].contentStart);
      const tstInfoBytes = content(b, eContentOctet);
      const tstTop = readTlv(tstInfoBytes, 0);
      const tstKids = children(tstInfoBytes, tstTop);
      result.policyOid = readOid(tstInfoBytes, tstKids[1]);
      const imprint = children(tstInfoBytes, tstKids[2]);
      result.messageImprintAlgorithm = readOid(tstInfoBytes, children(tstInfoBytes, imprint[0])[0]);
      result.messageImprintHex = toHex(content(tstInfoBytes, imprint[1]));
      result.serialNumber = readIntegerHex(tstInfoBytes, tstKids[3]);
      result.genTime = readGeneralizedTime(tstInfoBytes, tstKids[4]);
      for (let n = 5; n < tstKids.length; n++) {
        if (tstKids[n].tag !== 2) continue;
        result.nonceHex = readIntegerHex(tstInfoBytes, tstKids[n]);
        break;
      }
      if (expectedNonceHex !== null) {
        const strip = (h) => h.replace(/^(00)+/, "") || "0";
        const ok = result.nonceHex !== null && strip(result.nonceHex) === strip(expectedNonceHex.toLowerCase());
        add("nonce-echo", ok, ok ? "the authority echoed the nonce this request carried" : `the authority echoed ${(_a = result.nonceHex) != null ? _a : "no nonce"}, this request sent ${expectedNonceHex}`);
      }
      if (expectedHashHex === null) {
        add("message-imprint", true, `imprint ${result.messageImprintHex} (nothing to compare against)`);
      } else {
        const want = expectedHashHex.trim().toLowerCase();
        const ok = result.messageImprintHex === want;
        add("message-imprint", ok, ok ? `stamped over ${want}` : `stamped over ${result.messageImprintHex}, expected ${want}`);
      }
      const certs = [];
      for (const kid of sdKids) {
        if (kid.tag !== 160) continue;
        for (const c of children(b, kid)) {
          if (c.tag === 48) certs.push(parseCertificate(b, c));
        }
      }
      const signerInfos = sdKids[sdKids.length - 1];
      const si = children(b, signerInfos)[0];
      if (!si) {
        result.error = "token carries no SignerInfo";
        return result;
      }
      const siKids = children(b, si);
      const sid = siKids[1];
      const digestAlgOid = readOid(b, children(b, siKids[2])[0]);
      const digestName = DIGEST_BY_OID[digestAlgOid];
      if (!digestName) {
        result.error = `unsupported digest algorithm ${digestAlgOid}`;
        return result;
      }
      let idx = 3;
      let signedAttrs = null;
      if (((_b = siKids[idx]) == null ? void 0 : _b.tag) === 160) signedAttrs = siKids[idx++];
      const sigAlgOid = readOid(b, children(b, siKids[idx++])[0]);
      const signature = content(b, siKids[idx]);
      let signer = null;
      if (sid.tag === 48) {
        const sidKids = children(b, sid);
        const wantIssuer = bytesOf(b, sidKids[0]);
        const wantSerial = readIntegerHex(b, sidKids[1]);
        signer = (_c = certs.find((c) => c.serialHex === wantSerial && sameBytes(c.issuerDer, wantIssuer))) != null ? _c : null;
        if (!signer) {
          result.error = "the certificate the signature names is not in this token";
          return result;
        }
      } else if (sid.tag === 128) {
        const wantSki = toHex(content(b, sid));
        signer = (_d = certs.find((c) => c.subjectKeyIdentifierHex === wantSki)) != null ? _d : null;
        if (!signer) {
          result.error = "the certificate the signature names by key identifier is not in this token";
          return result;
        }
      }
      if (!signer) {
        result.error = "the signature does not name a certificate in a form this checker reads";
        return result;
      }
      result.signerSubject = signer.subjectString;
      result.signerCertSha256 = toHex(await digest("SHA-256", signer.der));
      if (!signedAttrs) {
        add("signed-attrs-digest", false, "token has no signed attributes");
      } else {
        let messageDigestAttr = null;
        let contentTypeOk = false;
        for (const attr of children(b, signedAttrs)) {
          const kids = children(b, attr);
          const oid = readOid(b, kids[0]);
          const values = children(b, kids[1]);
          if (oid === OID_ATTR_MESSAGE_DIGEST && values[0]) {
            messageDigestAttr = content(b, values[0]);
          } else if (oid === OID_ATTR_CONTENT_TYPE && values[0]) {
            contentTypeOk = readOid(b, values[0]) === OID_CT_TST_INFO;
          }
        }
        const actual = await digest(digestName, tstInfoBytes);
        const ok = messageDigestAttr !== null && sameBytes(messageDigestAttr, actual) && contentTypeOk;
        add("signed-attrs-digest", ok, ok ? `${digestName} of the timestamp body matches the signed messageDigest attribute` : "the signed messageDigest attribute does not cover this timestamp body");
      }
      if (signedAttrs) {
        const attrsDer = Uint8Array.from(bytesOf(b, signedAttrs));
        attrsDer[0] = 49;
        const v = await verifyWithCert(signer, sigAlgOid, signature, attrsDer, digestName);
        add("signature", v.ok, v.ok ? `signed by the embedded certificate (${v.detail})` : `signature did not verify (${v.detail})`);
      } else {
        const v = await verifyWithCert(signer, sigAlgOid, signature, tstInfoBytes, digestName);
        add("signature", v.ok, v.ok ? `signed by the embedded certificate (${v.detail})` : v.detail);
      }
      const eku = signer.extendedKeyUsage.includes(OID_KP_TIMESTAMPING);
      add("timestamping-eku", eku && signer.ekuCritical, eku ? signer.ekuCritical ? "the certificate is marked, critically, for time stamping only" : "the certificate allows time stamping but the extension is not marked critical" : "the certificate is not marked for time stamping");
      if (result.genTime && signer.notBefore && signer.notAfter) {
        const t = Date.parse(result.genTime);
        const from = Date.parse(signer.notBefore);
        const to = Date.parse(signer.notAfter);
        const ok = Number.isFinite(t) && t >= from && t <= to;
        add("genTime-in-cert-validity", ok, ok ? `${result.genTime} falls inside ${signer.notBefore} to ${signer.notAfter}` : `${result.genTime} falls outside ${signer.notBefore} to ${signer.notAfter}`);
      } else {
        add("genTime-in-cert-validity", false, "the token or the certificate has no readable time");
      }
      const chain = [signer];
      const links = [];
      let cursor = signer;
      for (let hop = 0; hop < certs.length; hop++) {
        if (sameBytes(cursor.subjectDer, cursor.issuerDer)) break;
        const issuer = certs.find((c) => sameBytes(c.subjectDer, cursor.issuerDer) && c !== cursor);
        if (!issuer) break;
        const v = await verifyWithCert(
          issuer,
          cursor.signatureAlgOid,
          cursor.signatureValue,
          cursor.tbsDer
        );
        links.push({ child: cursor, issuer, ok: v.ok, detail: v.detail });
        chain.push(issuer);
        cursor = issuer;
        if (!v.ok) break;
      }
      const terminal = chain[chain.length - 1];
      const selfSigned = sameBytes(terminal.subjectDer, terminal.issuerDer);
      result.rootCertSha256 = toHex(await digest("SHA-256", terminal.der));
      if (links.length === 0) {
        add("issuer-signature", false, "the token does not carry the issuing certificate");
      } else {
        const bad = links.find((l) => !l.ok);
        add("issuer-signature", !bad, bad ? `a certificate in the chain was not signed by the one above it (${bad.detail})` : `${links.length} certificate link${links.length === 1 ? "" : "s"} verified, up to ${terminal.subjectString}` + (selfSigned ? " (self-signed)" : " (the token carries no certificate above this one)"));
      }
      const chainHolds = links.length > 0 && links.every((l) => l.ok);
      const name = chainHolds ? KNOWN_TSA_ROOTS[result.rootCertSha256] : void 0;
      result.knownRootName = name != null ? name : null;
      add("known-root", Boolean(name), name ? `the chain ends at ${name}` : !chainHolds ? "the certificate chain did not verify, so the authority at the top of it is not established" : `the chain ends at a certificate FeelingWise does not pin: ${terminal.subjectString}, SHA-256 ${result.rootCertSha256}. Compare it against the authority's published certificate.`);
    } catch (err) {
      result.error = `token verification failed: ${err.message}`;
      return result;
    }
    result.ok = result.checks.every((c) => c.ok || c.name === "known-root");
    return result;
  }
  function shortSubject(subject) {
    if (!subject) return null;
    const parts = subject.split(", ");
    const pick = parts.filter((p) => /^(CN|O)=/.test(p));
    return pick.length ? pick.join(", ") : subject;
  }
  async function verifyAnchorBase64(input, expectedHashHex) {
    const b64 = (input.tst || input.response || "").trim() || null;
    if (!b64) {
      return {
        ok: false,
        genTime: null,
        messageImprintHex: null,
        messageImprintAlgorithm: null,
        serialNumber: null,
        policyOid: null,
        nonceHex: null,
        signerSubject: null,
        signerCertSha256: null,
        rootCertSha256: null,
        knownRootName: null,
        checks: [],
        error: "anchor carries no token"
      };
    }
    let bytes;
    try {
      const bin = atob(b64.replace(/\s+/g, ""));
      bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    } catch {
      return {
        ok: false,
        genTime: null,
        messageImprintHex: null,
        messageImprintAlgorithm: null,
        serialNumber: null,
        policyOid: null,
        nonceHex: null,
        signerSubject: null,
        signerCertSha256: null,
        rootCertSha256: null,
        knownRootName: null,
        checks: [],
        error: "anchor token is not base64"
      };
    }
    try {
      const top = readTlv(bytes, 0);
      const first = readTlv(bytes, top.contentStart);
      if (first.tag === 48) {
        const parsed = parseTimeStampResp(bytes);
        if (parsed.status !== 0 && parsed.status !== 1) {
          return {
            ok: false,
            genTime: null,
            messageImprintHex: null,
            messageImprintAlgorithm: null,
            serialNumber: null,
            policyOid: null,
            nonceHex: null,
            signerSubject: null,
            signerCertSha256: null,
            rootCertSha256: null,
            knownRootName: null,
            checks: [{ name: "response-granted", ok: false, detail: `the authority refused, PKIStatus ${parsed.status}` }],
            error: null
          };
        }
        if (parsed.token) {
          const v = await verifyTimeStampToken(parsed.token, expectedHashHex);
          v.checks.unshift({ name: "response-granted", ok: true, detail: `PKIStatus ${parsed.status}` });
          return v;
        }
      }
    } catch {
    }
    return verifyTimeStampToken(bytes, expectedHashHex);
  }
  return __toCommonJS(rfc3161_exports);
})();
// ---- END RFC 3161 ----

/**
 * One time-stamp token, opened offline: the certificates travel inside it.
 * Three readings, as on the export's own page: verified under an authority
 * this checker recognises; verified under one it does not (anyone can run a
 * timestamping service and sign their own tokens, so that reading names the
 * certificate instead of calling the token good); failed.
 */
async function openToken(anchor, expectedHashHex) {
  const api = __FW_RFC3161__;
  let v;
  try {
    v = await api.verifyAnchorBase64({ tst: anchor.tstB64, response: anchor.responseB64 }, expectedHashHex);
  } catch (err) {
    return { ok: false, authority: null, signer: null, genTime: null, rootCertSha256: null, failed: [], error: String(err && err.message || err) };
  }
  return {
    ok: !!v.ok,
    authority: v.knownRootName || null,
    signer: api.shortSubject(v.signerSubject),
    genTime: v.genTime,
    rootCertSha256: v.rootCertSha256,
    failed: (v.checks || []).filter((c) => !c.ok).map((c) => c.name),
    error: v.error || null,
  };
}

/**
 * The chain anchors, each against the record hash it names, and the stamp
 * over the signing key against a digest RECOMPUTED from the key in the file,
 * never the digest the file states beside it. A verified token under an
 * unrecognised authority never dates the key.
 */
async function checkTimestamps(data, sha256) {
  const out = { anchors: [], keyGenesis: null };
  const anchors = (data.anchors || []).slice().sort((a, b) => a.anchoredChainPosition - b.anchoredChainPosition);
  for (const a of anchors) {
    const t = await openToken(a, a.anchoredIntegrityHash);
    out.anchors.push({ position: a.anchoredChainPosition, recordHash: a.anchoredIntegrityHash, provider: a.tsaProvider || null, ...t });
  }
  const kg = data.keyGenesis;
  if (kg && Array.isArray(kg.anchors) && kg.anchors.length) {
    const jwk = data.publicKeyJwk || {};
    const expected = await sha256((jwk.x || '') + '|' + (jwk.y || ''));
    const stamps = [];
    for (const a of kg.anchors) stamps.push({ provider: a.tsaProvider || null, ...(await openToken(a, expected)) });
    let existedBy = null; const who = [];
    for (const s of stamps) {
      if (!s.ok || !s.genTime || !s.authority) continue;
      if (who.indexOf(s.authority) < 0) who.push(s.authority);
      if (!existedBy || s.genTime < existedBy) existedBy = s.genTime;
    }
    out.keyGenesis = { expectedDigest: expected, statedDigest: kg.publicKeyDigest || null, existedBy, authorities: who, stamps };
  }
  return out;
}

/**
 * The same walk the embedded verifier makes (runVerification in
 * html-export.ts), without a page to paint: keys, every record, withheld
 * records on their markers, the chain, the anchors, the manifest.
 */
async function verifyExportText(text) {
  const { data, html } = parseExport(text);
  const v = createVerifier(provenanceDocument(html));
  const report = { state: 'failed', manifest: 'missing', records: 0, keys: 0, failures: [], unverified: { priorKey: 0, unsigned: 0, signatureUnverified: 0, signatureRejected: 0 }, carriedKey: 0, redacted: 0, chain: null, anchors: null, coverage: null, notes: [] };

  let keySetup;
  try {
    keySetup = await v.importVerifiedPubKey(data.publicKeyJwk, data.publicKeyFingerprint);
  } catch (err) {
    report.failures.push({ index: -1, id: null, reason: 'key-setup', detail: String(err && err.message || err) });
    return report;
  }
  report.manifest = await v.checkManifest(data, keySetup.pubKey, keySetup.fingerprint);
  // 'no-rows' joins 'missing' and 'legacy' as a manifest that was not fully
  // checked rather than one that failed: a bare JSON envelope carries no page
  // rows to compare, which is a property of the input form, not evidence
  // against the file. Everything else in the manifest was still verified.
  if (report.manifest !== 'ok' && report.manifest !== 'missing' && report.manifest !== 'legacy' && report.manifest !== 'no-rows') {
    report.failures.push({ index: -1, id: null, reason: 'manifest', detail: report.manifest });
    return report;
  }
  const keys = {};
  keys[keySetup.fingerprint] = keySetup.pubKey;
  for (const carried of data.publicKeys || []) {
    try {
      const k = await v.importVerifiedPubKey(carried.jwk, carried.fingerprint);
      keys[k.fingerprint] = k.pubKey;
    } catch (_skip) { /* a carried key that fails its own fingerprint is left out; its records verify by hash only */ }
  }
  report.keys = Object.keys(keys).length;
  const records = Array.isArray(data.records) ? data.records : [];
  report.records = records.length;
  const redactions = v.redactionIndex(records);
  const perRecord = [];
  for (let i = 0; i < records.length; i++) perRecord.push(await v.verifyOne(records[i], keys, keySetup.fingerprint, redactions));
  const markerOk = {};
  for (let i = 0; i < records.length; i++) if (records[i] && records[i].kind === 'redaction-marker') markerOk[records[i].id] = !!(perRecord[i] && perRecord[i].ok);
  for (let i = 0; i < perRecord.length; i++) { const p = perRecord[i]; if (p && p.redacted && markerOk[p.markerId] === false) perRecord[i] = { ok: false, reason: 'redaction-unattested' }; }
  for (let i = 0; i < perRecord.length; i++) {
    const p = perRecord[i];
    if (!p.ok) { report.failures.push({ index: i, id: records[i] && records[i].id || null, reason: p.reason }); continue; }
    if (p.redacted) report.redacted++;
    if (p.carriedKey) report.carriedKey++;
    if (p.unverified) {
      if (p.unsigned) report.unverified.unsigned++;
      else if (p.priorKey) report.unverified.priorKey++;
      else if (p.signatureRejected) report.unverified.signatureRejected++;
      else report.unverified.signatureUnverified++;
    }
  }
  report.chain = await v.verifyChain(records, perRecord);
  report.anchors = v.anchorFindings(records, data.anchors || []);
  report.coverage = v.coverageFromRecords(records);
  // What the file says it is (selectionOf in the core): a report states how
  // many records it holds of how many the install had; the whole record
  // states nothing and holds everything the install still had.
  const sel = v.selectionOf(data, records);
  const keyStamped = !!(data.keyGenesis && Array.isArray(data.keyGenesis.anchors) && data.keyGenesis.anchors.length);
  report.holding = {
    kind: sel ? 'report' : (html ? 'whole-record' : 'envelope'),
    records: records.length,
    included: sel ? sel.included : records.length,
    totalSource: sel ? sel.totalSource : null,
    leftOut: sel ? sel.leftOut : 0,
    generatedAt: data.manifest && typeof data.manifest.generatedAt === 'string' ? data.manifest.generatedAt : null,
    fwVersion: typeof data.fwVersion === 'string' ? data.fwVersion : null,
    fingerprint: keySetup.fingerprint,
    anchors: (data.anchors || []).length,
    keyStamped,
    // Is the "whole record" claim backed by anything this checker verified?
    // The kind above is decided by the ABSENCE of a selection field, which the
    // file itself supplies, so on its own it is the file's word. The signed
    // manifest is what turns it into a checked statement: its recordsDigest
    // covers the record set and its envelopeDigest covers the selection field.
    //
    // 'no-rows' counts here. checkManifest verifies recordsDigest and
    // envelopeDigest BEFORE it reaches the page rows, so a bare JSON envelope
    // whose only unchecked part is the rendered rows still has its record set
    // and its selection field verified — removing or reordering a record in one
    // breaks recordsDigest exactly as it does in the HTML.
    manifestOk: false,
  };
  report.holding.manifestOk = report.manifest === 'ok' || report.manifest === 'no-rows';
  let state = v.verificationState(perRecord, report.chain, { anchors: report.anchors, coverage: report.coverage, selection: sel });
  if ((report.manifest === 'missing' || report.manifest === 'legacy' || report.manifest === 'no-rows') && state === 'verified') state = 'partial';
  report.state = state;
  if (report.manifest === 'missing' || report.manifest === 'legacy') report.notes.push('no signed manifest: the file was made by a build before 2026-09-06, or the install could not sign it');
  if (report.manifest === 'no-rows') report.notes.push('this is a bare JSON envelope: everything in the manifest was checked except the digest over the page rows, which are not present in this form. Ask for the HTML export to check those too.');
  const seams = (report.chain.branches || 0) + (report.chain.restarts || 0);
  if (seams > 0) report.notes.push(seams + ' chain seam(s): the install signed records at positions it had already used, or restarted');
  if (report.chain.unattributed > 0) report.notes.push(report.chain.unattributed + ' seam(s) could not be attributed by signature');
  if (report.chain.outside > 0) {
    if (sel && report.chain.outside <= sel.leftOut) report.notes.push(report.chain.outside + ' record(s) link to records this report left out on purpose; it holds ' + sel.included + ' of the ' + sel.totalSource + ' the install had, chosen by its own gate, and says so under its signature. Ask for the whole record if you need everything.');
    else report.notes.push(report.chain.outside + ' record(s) name a predecessor that is not in this file');
  }
  // Content withheld. The reader is told plainly, because the headline verdict
  // says "every hash recomputed" and for these records it was not: their
  // content has left the file, so the hash cannot be recomputed and the record
  // stands on a signed redaction marker plus its own signature over that hash.
  // Counted since the marker shipped and printed nowhere until 2026-09-08.
  if (report.redacted > 0) report.notes.push(report.redacted + ' record(s) had fields withheld before this file was made: their content is not here, so their hash was not recomputed. Each one is named by a signed redaction marker in this file and its signature over that hash was checked.');
  if (report.holding.anchors === 0 && !keyStamped) report.notes.push('no independent time stamp in this file: no chain anchor from a public authority and no stamp over the signing key; nothing here shows when these records existed beyond what the install wrote');
  if (report.anchors.notInFile > 0) report.notes.push(report.anchors.notInFile + ' independently timestamped record(s) are not in this file');
  if (report.anchors.beyondTail > 0) report.notes.push('an independent timestamp names position ' + report.anchors.beyondPosition + ', past the last record here');
  report.timestamps = await checkTimestamps(data, v.sha256);
  return report;
}

function describeTimestamps(ts, lines) {
  if (!ts) return;
  if (ts.anchors.length) {
    const known = ts.anchors.filter((a) => a.ok && a.authority);
    const unknown = ts.anchors.filter((a) => a.ok && !a.authority);
    const failed = ts.anchors.filter((a) => !a.ok);
    lines.push('Time-stamp tokens over the chain: ' + ts.anchors.length + ' opened; ' + known.length + ' verified under a recognised authority'
      + (known.length ? ' (' + Array.from(new Set(known.map((a) => a.authority))).join(', ') + ')' : '')
      + '; ' + unknown.length + ' under an authority this checker does not recognise; ' + failed.length + ' failed.');
    for (const a of unknown) lines.push('  position ' + a.position + ': signed by ' + (a.signer || 'an unnamed certificate') + ', root ' + (a.rootCertSha256 || '?') + '; anyone can run a timestamping service, so this token dates nothing on its own.');
    for (const a of failed) lines.push('  position ' + a.position + ': failed ' + (a.failed.length ? a.failed.join(', ') : (a.error || 'unknown')) + '.');
  }
  if (ts.keyGenesis) {
    const g = ts.keyGenesis;
    if (g.existedBy) lines.push('The signing key existed no later than ' + g.existedBy + ' (' + g.authorities.join(', ') + '), by a token over the key as it is in this file.');
    else lines.push('The stamp over the signing key did not verify under a recognised authority; the key is not dated by this file.');
  }
}

function describeHolding(h) {
  if (!h) return null;
  const when = h.generatedAt ? ', made ' + h.generatedAt.replace('T', ' ').replace(/\.\d+Z$/, ' UTC') : '';
  const by = h.fwVersion ? ' by ' + h.fwVersion : '';
  const key = h.fingerprint ? ', key ' + h.fingerprint : '';
  const stamps = h.anchors > 0 || h.keyStamped ? ', ' + h.anchors + ' independent time stamp(s)' + (h.keyStamped ? ' and a stamp over the key' : '') : ', no independent time stamp';
  // Completeness is the file's claim until a signed manifest makes it a checked
  // one. Without that manifest the chain walk cannot see records removed from
  // the END (nothing in the file points at them) nor a reordering (each link
  // still resolves, because the walk deliberately matches a predecessor
  // anywhere in the file — see verifyChain, which exists that way for a real
  // recovered chain holding 1,062 positions twice). Measured 2026-09-08 on the
  // demo with its manifest stripped: dropping the newest record, dropping the
  // oldest, and swapping two adjacent records all read chain ok, 0 failures.
  // With the manifest present all four tampering attempts are caught.
  //
  // So the checker must not print "everything the install still had" as its own
  // finding on a file it cannot check that on. It says whose claim it is.
  const unchecked = h.manifestOk ? '' : ' — the file\'s own claim, not checked here: with no signed manifest, records removed from the end or put out of order would not show';
  if (h.kind === 'report') return 'You are holding a report: ' + h.included + ' of the ' + h.totalSource + ' records the install had, ' + h.leftOut + ' left out by its own gate' + when + by + key + stamps + (h.manifestOk ? '' : unchecked) + '.';
  if (h.kind === 'whole-record') {
    return h.manifestOk
      ? 'You are holding the whole record: ' + h.records + ' record(s), everything the install still had' + when + by + key + stamps + '.'
      : 'The file says it is the whole record: ' + h.records + ' record(s)' + when + by + key + stamps + unchecked + '.';
  }
  return 'You are holding a bare envelope of ' + h.records + ' record(s)' + when + by + key + stamps + unchecked + '.';
}

function describe(report) {
  const lines = [];
  const holding = describeHolding(report.holding);
  if (holding) lines.push(holding);
  if (report.state === 'verified' && report.holding && report.holding.kind === 'report' && report.chain && report.chain.outside > 0) {
    lines.push('VERIFIED as a report of ' + report.holding.included + ' of ' + report.holding.totalSource + ' records: every hash recomputed and every signature checked under the ' + report.keys + ' key(s) this file carries; the signed manifest matches.');
  } else if (report.state === 'verified') {
    lines.push('VERIFIED: ' + report.records + ' record(s), every hash recomputed and every signature checked under the ' + report.keys + ' key(s) this file carries; the signed manifest matches.');
  } else if (report.state === 'partial') {
    // "no signature failed" is only sayable when none did. A signature that was
    // run and returned false is not a signature that could not be checked.
    lines.push('PARTIALLY VERIFIED: ' + report.records + ' record(s), no hash failed'
      + (report.unverified.signatureRejected > 0 ? '' : ' and no signature failed') + '.');
    if (report.unverified.priorKey > 0) lines.push('  ' + report.unverified.priorKey + ' record(s) verify by hash only: their signing key is not in this file.');
    if (report.unverified.unsigned > 0) lines.push('  ' + report.unverified.unsigned + ' record(s) carry no signature.');
    if (report.unverified.signatureUnverified > 0) lines.push('  ' + report.unverified.signatureUnverified + ' record(s) could not have their signature checked.');
    if (report.unverified.signatureRejected > 0) lines.push('  ' + report.unverified.signatureRejected + ' record(s) were checked and their signature did not verify; they name no key, so this may be a key that has since rotated rather than an edit, and it is not proof of either.');
    if (report.carriedKey > 0) lines.push('  ' + report.carriedKey + ' record(s) verify under a key that travelled in this file; the file cannot say whose key it is.');
  } else {
    const first = report.failures[0];
    if (first && first.index >= 0) lines.push('BROKEN at record ' + (first.index + 1) + ' (' + first.id + '): ' + first.reason + '.');
    else if (first) lines.push('BROKEN before any record was checked: ' + first.reason + (first.detail ? ' (' + first.detail + ')' : '') + '.');
    else lines.push('BROKEN.');
    if (report.failures.length > 1) lines.push('  ' + report.failures.length + ' record(s) failed in all.');
  }
  for (const n of report.notes) lines.push('  ' + n);
  describeTimestamps(report.timestamps, lines);
  lines.push(LIMIT_SENTENCE);
  return lines.join('\n');
}

const LIMIT_SENTENCE = 'This checks the file against itself. It does not establish who made the file, whether the key is the original key, or that the file is complete.';

/**
 * The same reading as describe(), laid out for a page: what the reader is
 * holding, the verdict as a band, the reasons and time stamps as a list, the
 * limit sentence, and the full report folded as data. Text goes in through
 * textContent only; nothing from the file is rendered as markup. The three
 * pages that check a file (verifier/index.html, the site's check pages) call
 * this and add nothing of their own, so the design is one and drift-locked.
 */
function render(report, root) {
  if (typeof document === 'undefined' || !root) return;
  while (root.firstChild) root.removeChild(root.firstChild);
  const el = (tag, cls, text) => {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text !== undefined && text !== null) e.textContent = String(text);
    return e;
  };
  const lines = describe(report).split('\n');
  const holding = report.holding ? lines.shift() : null;
  const verdict = lines.shift() || '';
  const rest = lines.filter((l) => l !== LIMIT_SENTENCE).map((l) => l.trim()).filter(Boolean);
  const card = el('div', 'fw-check fw-check-' + (report.state || 'failed'));
  if (holding) {
    const h = el('div', 'fw-check-holding');
    h.appendChild(el('div', 'fw-check-label', 'What you are holding'));
    h.appendChild(el('p', null, holding));
    card.appendChild(h);
  }
  const band = el('div', 'fw-check-verdict');
  band.appendChild(el('div', 'fw-check-label', 'What its own cryptography says'));
  band.appendChild(el('p', 'fw-check-verdict-line', verdict));
  card.appendChild(band);
  if (rest.length) {
    const list = el('ul', 'fw-check-notes');
    for (const line of rest) list.appendChild(el('li', null, line));
    card.appendChild(list);
  }
  card.appendChild(el('p', 'fw-check-limit', LIMIT_SENTENCE));
  const details = el('details', 'fw-check-raw');
  details.appendChild(el('summary', null, 'The full report as data'));
  details.appendChild(el('pre', null, JSON.stringify(report, null, 2)));
  card.appendChild(details);
  root.appendChild(card);
}



window.FWVerifier = { parseExport: parseExport, verifyExportText: verifyExportText, describe: describe, render: render };
})();
